

version: "3.8"
services:

  wmp2mqtt:
    image: ghcr.io/timbailey99/wmp2mqtt:latest
    container_name: wmp2mqtt
    environment:
      - MQTT_SERVER=mqtt://mqtt.bailey9.com
      - MQTT_USER=iot
      - MQTT_PASS=w4kz7nB6ACw5rp
      - RETAIN=true
      - WMP_IPS=192.168.100.14
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
